version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notice_board
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./nest-server
    container_name: nest-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/notice_board
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: front-app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
